src/BlogCoreEngine/Controllers/BlogController.cs
using BlogCoreEngine.Core.Entities;
using BlogCoreEngine.Core.Interfaces;
using BlogCoreEngine.Web.Extensions;
using BlogCoreEngine.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BlogCoreEngine.Controllers
{
    public class BlogController : Controller
    {
        private readonly IAsyncRepository<BlogDataModel> blogRepository;

        public BlogController(IAsyncRepository<BlogDataModel> blogRepository)
        {
            this.blogRepository = blogRepository;
        }

        #region View

        public async Task<IActionResult> View(Guid id)
        {
            var blog = await this.blogRepository.GetById(id);
            return View(blog);
        }

        #endregion

        #region New

        [Authorize(Roles = "Administrator")]
        public IActionResult New()
        {
            return View();
        }

        [Authorize(Roles = "Administrator"), HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> New(BlogViewModel blog)
        {
            if (ModelState.IsValid)
            {
                var newBlog = await this.blogRepository.Add(new BlogDataModel
                {
                    Id = Guid.NewGuid(),
                    Name = blog.Name,
                    Description = blog.Description,
                    Cover = blog.Cover.ToByteArray(),
                    Created = DateTime.Now,
                    Modified = DateTime.Now
                });

                return this.RedirectToAsync<BlogController>(x => x.View(newBlog.Id));
            }
            return View(blog);
        }

        #endregion

        #region Edit

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(Guid id)
        {
            return View(await this.blogRepository.GetById(id));
        }

        [Authorize(Roles = "Administrator"), HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, BlogDataModel blog, IFormFile formFile)
        {
            var targetBlog = await this.blogRepository.GetById(id);

            if (ModelState.IsValid)
            {
                targetBlog.Name = blog.Name;
                targetBlog.Description = blog.Description;

                if (!(formFile == null || formFile.Length <= 0))
                {
                    targetBlog.Cover = formFile.ToByteArray();
                }

                await this.blogRepository.Update(targetBlog);

                return this.RedirectToAsync<BlogController>(x => x.View(id));
            }

            blog.Cover = targetBlog.Cover;

            return View(blog);
        }

        #endregion

        #region Delete

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(Guid id)
        {
            await this.blogRepository.Remove(id);
            return this.RedirectToAsync<HomeController>(x => x.Index());
        }

        #endregion
    }
}

src/BlogCoreEngine/Controllers/CommentController.cs
using BlogCoreEngine.Core.Entities;
using BlogCoreEngine.Core.Interfaces;
using BlogCoreEngine.DataAccess.Data;
using BlogCoreEngine.DataAccess.Extensions;
using BlogCoreEngine.Web.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace BlogCoreEngine.Controllers
{
    public class CommentController : Controller
    {
        private readonly IAsyncRepository<CommentDataModel> commentRepository;
        private readonly UserManager<ApplicationUser> userManager;

        public CommentController(IAsyncRepository<CommentDataModel> commentRepository, UserManager<ApplicationUser> userManager)
        {
            this.commentRepository = commentRepository;
            this.userManager = userManager;
        }

        #region New

        [Authorize, HttpPost]
        public async Task<IActionResult> New(Guid id, string CommentText)
        {
            if (string.IsNullOrWhiteSpace(CommentText))
            {
                ModelState.AddModelError("", "Text field is required!");
                return this.RedirectToAsync<PostController>(x => x.Details(id));
            }

            await this.commentRepository.Add(new CommentDataModel
            {
                Content = CommentText,
                Created = DateTime.Now,
                Modified = DateTime.Now,
                AuthorId = User.Identity.GetAuthorId(),
                PostId = id
            });

            return this.RedirectToAsync<PostController>(x => x.Details(id));
        }

        #endregion

        #region Delete

        [Authorize]
        public async Task<IActionResult> Delete(Guid id)
        {
            var comment = await this.commentRepository.GetById(id);

            if (!(User.Identity.GetAuthorId() == comment.AuthorId || this.User.IsInRole("Administrator")))
            {
                return this.RedirectTo<HomeController>(x => x.NoAccess());
            }

            await this.commentRepository.Remove(id);

            return this.RedirectToAsync<PostController>(x => x.Details(comment.PostId.Value));
        }

        #endregion

        #region Edit

        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            var comment = await this.commentRepository.GetById(id);

            if (!(User.Identity.GetAuthorId() == comment.AuthorId || this.User.IsInRole("Administrator")))
            {
                return this.RedirectTo<HomeController>(x => x.NoAccess());
            }

            return View(comment);
        }

        [Authorize, HttpPost]
        public async Task<IActionResult> Edit(Guid id, CommentDataModel comment)
        {
            if (ModelState.IsValid)
            {
                var targetComment = await this.commentRepository.GetById(id);
                targetComment.Content = targetComment.Content;

                await this.commentRepository.Update(targetComment);

                return this.RedirectToAsync<PostController>(x => x.Details(comment.PostId.Value));
            }

            return View(comment);
        }

        #endregion
    }
}

src/BlogCoreEngine/Controllers/PostController.cs
using BlogCoreEngine.Core.Entities;
using BlogCoreEngine.Core.Interfaces;
using BlogCoreEngine.DataAccess.Data;
using BlogCoreEngine.DataAccess.Extensions;
using BlogCoreEngine.Web.Extensions;
using BlogCoreEngine.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading.Tasks;

namespace BlogCoreEngine.Controllers
{
    public class PostController : Controller
    {
        private readonly IAsyncRepository<PostDataModel> postRepository;
        private readonly UserManager<ApplicationUser> userManager;

        public PostController(IAsyncRepository<PostDataModel> postRepository, UserManager<ApplicationUser> userManager)
        {
            this.postRepository = postRepository;
            this.userManager = userManager;
        }

        #region Pin

        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Pin(Guid id)
        {
            var post = await this.postRepository.GetById(id);

            post.Pinned = !post.Pinned;
            await this.postRepository.Update(post);

            return this.RedirectToAsync<BlogController>(x => x.View(post.BlogId.Value));
        }

        #endregion

        #region Details

        public async Task<IActionResult> Details(Guid id)
        {
            var post = await this.postRepository.GetById(id);

            if (post != null)
            {
                post.Views += 1;
                await this.postRepository.Update(post);
            }

            return View(post);
        }

        #endregion

        #region Edit

        [Authorize]
        public async Task<IActionResult> Edit(Guid id)
        {
            var post = await this.postRepository.GetById(id);

            if (!(User.Identity.GetAuthorId() == post.AuthorId || this.User.IsInRole("Administrator")))
            {
                return this.RedirectTo<HomeController>(x => x.NoAccess());
            }

            return View(post);
        }

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, PostDataModel postDataModel, IFormFile formFile)
        {
            var post = await this.postRepository.GetById(id);

            if (ModelState.IsValid)
            {
                if (post != null)
                {
                    post.Title = postDataModel.Title;
                    post.Preview = postDataModel.Preview;
                    post.Content = postDataModel.Content;
                    post.Modified = DateTime.Now;
                    post.Link = postDataModel.Link;

                    if (formFile != null)
                    {
                        post.Cover = formFile.ToByteArray();
                    }
                }

                await this.postRepository.Update(post);

                return this.RedirectToAsync<BlogController>(x => x.View(post.BlogId.Value));
            }

            postDataModel.Title = post.Title;
            postDataModel.Content = post.Content;
            postDataModel.Cover = post.Cover;

            return View(postDataModel);
        }

        #endregion

        #region New

        [Authorize]
        public IActionResult New(Guid id) => View();

        [Authorize, HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> New(Guid id, PostViewModel post)
        {
            if (ModelState.IsValid)
            {
                var newPost = await this.postRepository.Add(new PostDataModel
                {
                    Id = Guid.NewGuid(),
                    AuthorId = User.Identity.GetAuthorId(),
                    BlogId = id,
                    Created = DateTime.Now,
                    Modified = DateTime.Now,
                    Archieved = false,
                    Pinned = false,
                    Preview = post.Preview,
                    Link = post.Link,
                    Title = post.Title,
                    Views = 0,
                    Cover = post.Cover.ToByteArray(),
                    Content = post.Text
                });

                return this.RedirectToAsync<PostController>(x => x.Details(newPost.Id));
            }

            return View(post);
        }

        [Authorize(Roles = "Administrator"), HttpPost]
        public async Task<IActionResult> Steal(Guid id, string WebsiteUrl)
        {
            var post = new PostDataModel
            {
                Title = WebsiteUrl,
                Preview = WebsiteUrl,
                Link = WebsiteUrl,
                BlogId = id,
                AuthorId = User.Identity.GetAuthorId()
            };

            var request = WebRequest.Create(WebsiteUrl) as HttpWebRequest;
            var response = request.GetResponse() as HttpWebResponse;

            if (response.StatusCode == HttpStatusCode.OK)
            {
                var receiveStream = response.GetResponseStream();
                var readStream = response.CharacterSet == null ? new StreamReader(receiveStream) :
                    new StreamReader(receiveStream, Encoding.GetEncoding(response.CharacterSet));

                post.Content = readStream.ReadToEnd();

                response.Close();
                readStream.Close();
            }

            await this.postRepository.Add(post);
            return this.RedirectToAsync<BlogController>(x => x.View(id));
        }

        #endregion

        #region Archiv

        [Authorize]
        public async Task<IActionResult> Archiv(Guid id)
        {
            var post = await this.postRepository.GetById(id);

            if (!((User.Identity.GetAuthorId() == post.AuthorId) || this.User.IsInRole("Administrator")))
            {
                return this.RedirectTo<HomeController>(x => x.NoAccess());
            }

            post.Archieved = !post.Archieved;
            await this.postRepository.Update(post);

            return this.RedirectToAsync<PostController>(x => x.Details(post.Id));
        }

        #endregion

        #region Delete

        [Authorize]
        public async Task<IActionResult> Delete(Guid id)
        {
            var post = await this.postRepository.GetById(id);

            if (!((User.Identity.GetAuthorId() == post.AuthorId) || this.User.IsInRole("Administrator")))
            {
                return this.RedirectTo<HomeController>(x => x.NoAccess());
            }

            await this.postRepository.Remove(id);

            return this.RedirectToAsync<BlogController>(x => x.View(post.BlogId.Value));
        }

        #endregion
    }
}

src/BlogCoreEngine/Views/Shared/_BlogPartial.cshtml
@model BlogCoreEngine.Core.Entities.BlogDataModel

@{
}

<div class="row-c">
    <div>
        <ul>
            @if (!Model.Posts.Any() && !Model.Posts.Where(x => x.Pinned).Any())
            {
                <div class="container" style="margin-top: 26.9px; min-width: 750px">
                    <h1>No Posts found!</h1>
                    <a class="clickLink" asp-controller="Post" asp-action="New" asp-route-id="@Model.Id">New Post</a>
                </div>
            }
            else
            {
                if (Model.Posts.Where(x => x.Pinned).Any())
                {
                    <h1 class="bubble">Pinned</h1>
                    @foreach (var post in Model.Posts.Where(x => x.Pinned))
                    {
                        <li>
                            @{ await Html.RenderPartialAsync("_PostPartial", post); }
                        </li>
                    }
                }

                <h1 class="bubble">Last Posts</h1>
                @foreach (var post in Model.Posts.Where(x => x.Pinned == false))
                {
                    <li>
                        @{ await Html.RenderPartialAsync("_PostPartial", post); }
                    </li>
                }
            }
        </ul>
    </div>

    <div class="container" style="width: 250px; margin-left: 10px; height: 300px; margin-top: 26.9px">
        <h4 class="bubble" style="margin-bottom: 15px">Info</h4>
        <img style="height: 80px; margin-bottom: 10px" src="data:image;base64,@System.Convert.ToBase64String(Model.Cover)" />
        <h2 style="text-align: center"><strong>@Model.Name</strong></h2>

        <p style="font-size: 13px; text-align: center;">@Model.Description</p>
        <p style="margin-top: 20px; font-size: 13px; color: gray;">Posts: @Model.Posts.Count()</p>

        <hr />

        <div style="text-align: center">
            <a class="clickLink" asp-controller="Post" asp-action="New" asp-route-id="@Model.Id">New Post</a>

            @if (User.IsInRole("Administrator"))
            {
                <a style="margin-left: 10px" class="clickLink" asp-controller="Blog" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
            }
        </div>
    </div>
</div>

src/BlogCoreEngine/Views/Shared/_CommentPartial.cshtml
@model BlogCoreEngine.Core.Entities.CommentDataModel

<div class="CommentLi">
    <div class="CommentMain">
        <div class="CommentLeft">
            <img src="data:image;base64,@System.Convert.ToBase64String(Model.Author.Image)" />
            <a style="margin-bottom: 10px;" asp-controller="Account" asp-action="Profile" asp-route-id="@Model.Author.Name"><strong>@Model.Author.Name</strong></a>

            @if (Model.Post.AuthorId == Model.AuthorId)
            {
                <h6>Author</h6>
            }

            <h3 style="color: gray; font-size: 11px">Posts: @(Model.Author.Posts.Count() + Model.Author.Comments.Count())</h3>
        </div>

        <div class="CommentRight">
            <div class="headline">
                <h3 style="color: gray; font-size: 12px">@Model.Created.ToString("dd.MM.yyyy · HH:mm")</h3>
            </div>

            <div class="content">
                @Html.Raw(Model.RenderContent())
            </div>

            <div class="underline">
                @if (User.Identity.GetAuthorId() == Model.AuthorId || User.IsInRole("Administrator"))
                {
                    <a style="margin-right: 10px;" class="clickLink" asp-controller="Comment" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                    <a class="clickLink" style="color: red;" asp-controller="Comment" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                }
            </div>
        </div>
    </div>
</div>

src/BlogCoreEngine/Views/Shared/_Layout.cshtml
@inject BlogCoreEngine.Core.Interfaces.IBlogOptionService blogOptionService;

<!DOCTYPE html>

<html lang="en">

<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <meta name="author" content="Moritz Müller" />
    <meta name="description" content="BlogCoreEngine" />

    <link rel="icon" href="data:image;base64,@System.Convert.ToBase64String(await blogOptionService.GetLogo())" />

    <link rel="stylesheet" href="~/css/Site.css" />
    <link rel="stylesheet" href="~/css/Comment.css" />
    <link rel="stylesheet" href="~/css/Post.css" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <!-- include libraries(jQuery, bootstrap, fontawesome) -->
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
    <link href="http://netdna.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.css" rel="stylesheet">

    <title>@await blogOptionService.GetTitle()</title>
</head>

<body>
    <header>
        <div class="topbar">
            <div class="logo">
                <a asp-controller="Home" asp-action="Index">
                    <img src="data:image;base64,@System.Convert.ToBase64String(await blogOptionService.GetLogo())" alt="LOGO" />
                </a>
            </div>

            <div class="branding">
                <h1><a asp-controller="Home" asp-action="Index">@await blogOptionService.GetTitle()</a></h1>
            </div>

            <div class="searchbar">
                <form asp-controller="Home" asp-action="Search" method="post" style="min-width: initial">
                    <img src="~/images/Search.jpg" height="22" width="22" />
                    <input type="text" name="searchString" />
                </form>
            </div>

            <div class="login">
                @if (User.Identity.IsAuthenticated)
                {
                    <a class="clickLink" asp-controller="Account" asp-action="Profile" asp-route-id="@User.Identity.GetAuthorName()">@User.Identity.GetAuthorName()</a>
                    <a class="clickLink" asp-controller="Account" asp-action="LogOutAsync">Logout</a>
                }
                else
                {
                    <a class="clickLink" asp-controller="Account" asp-action="Login">Login</a>
                    <a class="buttonLink" asp-controller="Account" asp-action="Register">Register</a>
                }
            </div>

            <div class="navigator">
                <nav>
                    <ul>
                        @if (this.User.IsInRole("Administrator"))
                        {
                            <li><a class="clickLink" asp-controller="Home" asp-action="AdminPanel">Admin Panel</a></li>
                        }
                    </ul>
                </nav>
            </div>
        </div>
    </header>

    <div class="main-container">
        @RenderBody()
    </div>

    <footer>
        <div class="footer-container">
            <a href="https://github.com/moritz-mm/BlogCoreEngine">BlogCoreEngine on GitHub</a>
        </div>
    </footer>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="~/js/Main.js"></script>
</body>
</html>

src/BlogCoreEngine/Views/Shared/_PostDetailsPartial.cshtml
@model BlogCoreEngine.Core.Entities.PostDataModel

<div>
    <h2><a asp-controller="Post" asp-action="Details" asp-route-id="@Model.Id"><strong>@Model.Title</strong></a></h2>

    <hr />

    <div class="headline">
        <a style="font-size: 13px" asp-controller="Blog" asp-action="View" asp-route-id="@Model.BlogId">@Model.Blog.Name</a>
        <p style="margin-left: 6px; font-size: 13px">·</p>
        <a style="color: gray; margin-left: 6px; font-size: 13px" asp-controller="Account" asp-action="Profile" asp-route-id="@Model.Author.Name">Posted by @Model.Author.Name</a>
        <p style="margin-left: 6px; font-size: 13px">·</p>
        <h2 style="color: gray; margin-left: 6px; font-size: 13px">@Model.Created.ToString("dd.MM.yyyy")</h2>

        @if (Model.Archieved)
        {
            <i class="far fa-file-archive" style="margin-top: 1.8px; margin-left: 8px;"></i>
        }

        @if (Model.Pinned)
        {
            <i class="fas fa-paperclip" style="margin-top: 1.8px; margin-left: 8px;"></i>
        }

        @if (!string.IsNullOrWhiteSpace(Model.Link))
        {
            @if (Model.Link.Length > 30)
            {
                <a class="clickLink" style="margin-left: 10px; margin-top: 1px; font-size: 11px;" href="@Model.Link">@Model.Link.Substring(0, 30)...</a>
            }
            else
            {
                <a class="clickLink" style="margin-left: 10px; margin-top: 1px; font-size: 11px;" href="@Model.Link">@Model.Link</a>
            }
        }
    </div>

    <div class="content">
        @Html.Raw(Model.RenderContent())
    </div>

    <div class="underline">
        <a class="clickLink" asp-controller="Blog" asp-action="View" asp-route-id="@Model.BlogId">Back</a>
        <h1 style="color: gray;">@Model.Views Views</h1>
        <h1><strong>@Model.Comments.Count()</strong> Comments</h1>

        @if (User.Identity.IsAuthenticated && User.Identity.GetAuthorId() == Model.AuthorId || User.IsInRole("Administrator"))
        {
            <a class="clickLink" asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
            <a class="clickLink" style="color: red" asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
            <a class="clickLink" style="color: darkkhaki" asp-controller="Post" asp-action="Archiv" asp-route-id="@Model.Id">Archiv</a>
        }
    </div>

    @if (Model.Archieved)
    {
        <div style="border-left: 2.5px solid Gold; text-align: center; padding: 5px; background-color: papayawhip; margin-top: 20px;" class="column-container">
            <p>New comments cannot be posted</p>
            <p>This thread has been locked by the <strong>Creator</strong> or <strong>Admin</strong></p>
        </div>
    }
</div>

src/BlogCoreEngine/Views/Shared/_PostPartial.cshtml
@model BlogCoreEngine.Core.Entities.PostDataModel

<div class="BlogLi">
    <div class="BlogMain">
        <div class="BlogCover">
            @if (string.IsNullOrWhiteSpace(Model.Link))
            {
                <a asp-controller="Post" asp-action="Details" asp-route-id="@Model.Id">
                    <img src="data:image;base64,@System.Convert.ToBase64String(Model.Cover)" />
                </a>
            }
            else
            {
                <a href="@Model.Link">
                    <img src="data:image;base64,@System.Convert.ToBase64String(Model.Cover)" />
                </a>
            }
        </div>

        <div class="BlogContent">
            <div class="row-c">
                <h2><a asp-controller="Post" asp-action="Details" asp-route-id="@Model.Id"><strong>@Model.Title</strong></a></h2>
            </div>

            <div class="headline">
                <a style="font-size: 13px" asp-controller="Blog" asp-action="View" asp-route-id="@Model.BlogId">@Model.Blog.Name</a>
                <p style="margin-left: 6px; font-size: 13px">·</p>
                <a style="color: gray; margin-left: 6px; font-size: 13px" asp-controller="Account" asp-action="Profile" asp-route-id="@Model.Author.Name">Posted by @Model.Author.Name</a>
                <p style="margin-left: 6px; font-size: 13px">·</p>
                <h2 style="color: gray; margin-left: 6px; font-size: 13px">@Model.Created.ToString("dd.MM.yyyy")</h2>

                @if (Model.Archieved)
                {
                    <i class="far fa-file-archive" style="margin-top: 1.8px; margin-left: 8px;"></i>
                }

                @if (Model.Pinned)
                {
                    <i class="fas fa-paperclip" style="margin-top: 1.8px; margin-left: 8px;"></i>
                }

                @if (!string.IsNullOrWhiteSpace(Model.Link))
                {
                    @if (Model.Link.Length > 30)
                    {
                        <a class="clickLink" style="margin-left: 10px; margin-top: 1px; font-size: 11px;" href="@Model.Link">@Model.Link.Substring(0, 30)...</a>
                    }
                    else
                    {
                        <a class="clickLink" style="margin-left: 10px; margin-top: 1px; font-size: 11px;" href="@Model.Link">@Model.Link</a>
                    }
                }
            </div>

            @if (!string.IsNullOrWhiteSpace(Model.Preview))
            {
                <div class="preview">
                    <p>@Html.Raw(Model.RenderPreview()) <a class="clickLink" style="margin-left: 5px" asp-controller="Post" asp-action="Details" asp-route-id="@Model.Id"> Read more...</a></p>
                </div>
            }

            <div class="underline">
                <h1 style="color: gray;">@Model.Views Views</h1>
                <h1><strong>@Model.Comments.Count()</strong> Comments</h1>

                @if (User.Identity.IsAuthenticated)
                {
                    @if (User.Identity.GetAuthorId() == Model.AuthorId || User.IsInRole("Administrator"))
                    {
                        <a class="clickLink" asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
                        <a class="clickLink" style="color: red" asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                    }

                    @if (User.IsInRole("Administrator"))
                    {
                        @if (Model.Pinned)
                        {
                            <a class="clickLink" style="color: darkkhaki" asp-controller="Post" asp-action="Pin" asp-route-id="@Model.Id">Unpin</a>
                        }
                        else
                        {
                            <a class="clickLink" style="color: darkkhaki" asp-controller="Post" asp-action="Pin" asp-route-id="@Model.Id">Pin</a>
                        }
                    }
                }
            </div>
        </div>
    </div>
</div>